### ISSUE TITLE
XPlot relies on things that are not .NET Standard

### ISSUE THREAD

**Issue by dsyme** [fslaborg/XPlot#79]
Looks like XPlot.GoogleCharts can only be .NET Standard if `Google.DataTable.Net.Wrapper` is also update to be .NET Standard

C:\GitHub\dsyme\XPlot\src\XPlot.GoogleCharts\XPlot.GoogleCharts.fsproj : warning NU1701: Package 'Google.DataTable.Net.Wrapper 3.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\GitHub\dsyme\XPlot\XPlot.sln]

Also GoogleCharts.Deedle --> Deedle, but I don't mind about that one so much since I want to get rid of it, and there is a .NET Standard Deedle being prepared in any case

```
C:\GitHub\dsyme\XPlot\src\XPlot.GoogleCharts.Deedle\XPlot.GoogleCharts.Deedle.fsproj : warning NU1701: Package 'Deedle 1.2.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\GitHub\dsyme\XPlot\XPlot.sln]
    9 Warning(s)
```

**Comment by jackfoxy** [comment]
https://github.com/zoranmax/GoogleDataTableLib/issues/1

**Comment by zoranmax** [comment]
Hi, I started working on porting the library to .NET Standard 2.0. For the time being i don't have a definitive ETA for it, as I need to support also the standard .NET 3.5 version for which the library was written. 
I hope this is not causing you too much issues for the time being?

**Comment by zoranmax** [comment]
Hi,
Actually, I had some free time  to spend on this.
I published a pre-release on nuget. Can you test it out?
https://www.nuget.org/packages/Google.DataTable.Net.Wrapper/4.0.0-rc1

There should be NO breaking changes, just a pure port.
Regards,
Zoran

**Comment by jackfoxy** [comment]
@zoranmax  I just verified pointing to Google.DataTable.Net.Wrapper/4.0.0-rc1 builds the solution without the compatibility warning messages. 

Unfortunately I have no time in the next couple of weeks to do any real testing. 

I have put the word out on twitter looking for testers. https://twitter.com/foxyjackfox/status/1038457520111595520

**Comment by zoranmax** [comment]
Hi ,
Did you have a chance to look into this?

Regards,
Zoran

**Comment by jackfoxy** [comment]
@zoranmax  sorry for the hold-up, I'm trying to make progress on https://github.com/fslaborg/XPlot/issues/78 as well. I think that one may have to wait until FSI is supported in netstandard2.0, which should be pretty soon.

Since I did get Google.DataTable.Net.Wrapper/4.0.0-rc1  to build cleanly, it probably works.

**Comment by jackfoxy** [comment]
@zoranmax Sorry for long delay. I finally got a netcoreapp2.1 test project running, and I'm pretty sure this is not working. Unfortunately my test has proprietary connections I cannot share. I'll try to come up with a simpler test project...but that will take a while. 

````
Unhandled Exception: System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at XPlot.GoogleCharts.GoogleChart.Show()
   at Histograms.HistogramsConsole.chartStats@170-1.Invoke(IEnumerable`1 statistics, Double median, Double stdDev) in C:\...\HistogramsConsole\Program.fs:line 199
   at Histograms.HistogramsConsole.main(String[] argv) in C:\...\HistogramsConsole\Program.fs:line 257
````

````at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)```` are you starting dotnet here?

I'll try investigating deeper when I can.

**Comment by zyzhu** [comment]
@jackfoxy @zoranmax @dsyme I've found that the problem does not lie in the latest Google.DataTable.Net.Wrapper but at Chart.Show in XPlot.

`System.Diagnostics.Process.Start(path)` does not work on netcore app as it shall check which OS it runs and run differently on different OS. I've replaced it in the pull #83

I've also updated other dependencies, removed appveyor source for FSharp.Formatting.

I've also fixed dll path for all scripts. But fixing docs generation depends on FAKE supporting fsiEvaluator parameter. I have no idea how to proceed on that pull request.

I've tested both XPlot.Plotly and XPlot.GoogleCharts on my local projects and a netcoreapp testing project and it all works. Please take a look and it's worth releasing a new version so that dependencies are all on netstandard.

**Comment by jackfoxy** [comment]
thanks, @zyzhu  I will try to find the time to review and merge. If some other maintainer gets to it before me, that is fine. Ping again if you think I am taking too long.

**Comment by jackfoxy** [comment]
@zyzhu I'll try to test this against my Windows project that uses XPlot this week. 
Note GenerateDocs is still broken, Time permitting I will take a look at this again. https://github.com/fslaborg/XPlot/issues/78

**Comment by jackfoxy** [comment]
@dsyme I have a netstandard2.0 build working in my F# project consuming XPlot in a Windows environment. I don't do anything in non-Windows.
What are you thoughts on calling this v2.0 and releasing to Nuget?
 
cc @zoranmax  @zyzhu

**Comment by dsyme** [comment]
@jackfoxy That would be great, please let's do that!

**Comment by jackfoxy** [comment]
I'm calling this closed. XPlot.GoogleCharts, XPlot.Plotly, and XPlot.GoogleCharts.Deedle v2.0 have all been pushed to Nuget.
Thanks to @zoranmax  and @zyzhu  
 
If any related issue arise, please open new issue.
